name: Forward Merge
description: Forward Merge to specified branch
inputs:
  from:
    description: "The source branch to merge from."
    required: true
  to:
    description: "The target branch to merge to."
    required: true
runs:
  using: "composite"
  steps:
    # Add action path to $PATH
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    # Forwards merge using forward-merge.sh
    - run: forward-merge.sh
      shell: bash
      env:
        MERGE_FROM: ${{ inputs.from }}
        FORWARD_TO: ${{ inputs.to }}
