name: Forward Merge
description: Forward Merge to specified branch
inputs:
  branch:
    description: "Branch to merge to"
    required: true
runs:
  using: "composite"
  steps:
    # Forwards merge using forward-merge.sh
    - id: forward-merge
      shell: bash
      run: forward-merge.sh
      env:
        FORWARD_TO: ${{ inputs.branch }}
